# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "../", "/vagrant"

  config.vm.provider "virtualbox" do |v|
    v.name = "job_scrapper"
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.provision "shell", path: "bootstrap.sh"

end
